# Generated by Django 6.0.2 on 2026-08-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
