# Generated by Django 6.0 on 2026-01-30 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardSettings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='board_settings', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('view_mode', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10)),
                ('last_changed', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Board Settings',
            },
        ),
    ]
